config/routes.rb
Rails.application.routes.draw do
  

  

  resources :books do 
    resources :reviews
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
	has_many :reviews

	def self.last_created_books(n)
		order(created_at: :desc).limit(n)
	end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :book

	validates :rating, presence: true
	validates :review, presence: true 
	validates :rating, {numericality: true}
	validates_associated :book

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
    def index
  	@books = Book.last_created_books(10)
  	if @books.empty? 
  		render 'no_projects_found'
  	end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
  	@book = Book.find params[:book_id]
  	@reviews = @book.reviews
  end

  def new 
  	@book = Book.find params[:book_id]
  	@review = @book.reviews.new
  end

  def create
  	@book = Book.find params[:book_id]
  	@review = @book.reviews.new entry_params

  	if @review.save
  		redirect_to action: 'index', controller: "reviews",
  		book_id: @book.id
  	else 
  		render 'new'
  	end

  end 

  private

  def entry_params
  	params.require(:review).permit(:review, :rating)
  end

end

app/controllers/site_controller.rb
class SiteController < ApplicationController
	def home
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/books/index.html.erb
<h1>Books#index</h1>




<ul>
	<% @books.each do |book| %>
		<li> Title : <%= book.title%> --  Descritpion : <%=book.description%> -- Price 
			<%=book.price%>----- 
			<%= link_to('Reviews', book_reviews_path(book.id))%>
		</li>		
	<%end%>
	
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/index.html.erb
<h1><%= @book.title%></h1>
<ul>
	<%@reviews.each do |review|%>
			<li>
				Review: <%=review.review%> 
				Rated: <%=review.rating%> 
			</li><br>
	<%end%>
	
</ul>
<%= link_to('Add a Review', new_book_review_path(@book))%>
<%= link_to('front page', books_path)%>

app/views/reviews/new.html.erb
<%= form_for [@book, @review] do |f|%>
	<%= f.label :review %>
	<%= f.text_field :review %>
	<br>
	<%= f.label :rating %>
	<%= f.text_field :rating, size: 4 %>
	<br>
	<%= f.submit 'Save' %>
	<%= link_to 'Cancel', book_reviews_path(@book.id)%>

<%end%>

<% if @review.errors.any? %>
	<ul>
		<% @review.errors.full_messages.each do |review_msg|%>
			<li><%= review_msg%></li>
		<%end%>
	</ul>
<%end%>

app/views/site/home.html.erb
<h1>Welcome</h1>


<form action="/books" method ="post" enctype = "multipart/form-data">
	
	<input type="text" placeholder="search for a book" id="seachbar">
	<button type="sumbit">search</button>
</form>